// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackNGoMati.Models;

#nullable disable

namespace TrackNGoMati.Migrations
{
    [DbContext(typeof(TrackNgoDbContext))]
    [Migration("20260702200710_Phase5_Polish")]
    partial class Phase5_Polish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackNGoMati.Models.AuditTrailEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_AuditTrailEntries_DocumentId");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditTrailEntries_UserId");

                    b.ToTable("AuditTrailEntries");
                });

            modelBuilder.Entity("TrackNGoMati.Models.CitizenFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CitizenFeedbacks");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HeadUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DepartmentCode" }, "IX_Departments_DepartmentCode")
                        .IsUnique();

                    b.HasIndex(new[] { "HeadUserId" }, "IX_Departments_HeadUserId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DigitalSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SignatureImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SignedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DigitalSignatures_DocumentId");

                    b.HasIndex(new[] { "SignedByUserId" }, "IX_DigitalSignatures_SignedByUserId");

                    b.ToTable("DigitalSignatures");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtaprocessingDays")
                        .HasColumnType("int")
                        .HasColumnName("ARTAProcessingDays");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentOfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStepIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFiled")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EscalationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginatingDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("QrcodePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QRCodePath");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UrgencyJustification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_Documents_CreatedByUserId");

                    b.HasIndex(new[] { "CurrentStatus" }, "IX_Documents_CurrentStatus");

                    b.HasIndex(new[] { "DateFiled" }, "IX_Documents_DateFiled");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Documents_DepartmentId");

                    b.HasIndex(new[] { "SubmittedByUserId" }, "IX_Documents_SubmittedByUserId");

                    b.HasIndex(new[] { "TrackingNumber" }, "IX_Documents_TrackingNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "TypeId" }, "IX_Documents_TypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentAttachments_DocumentId");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnchorLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RemarkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkflowState")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentComments_DocumentId");

                    b.HasIndex(new[] { "UserId" }, "IX_DocumentComments_UserId");

                    b.ToTable("DocumentComments");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryFlags")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConferenceName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentMetadatas_DocumentId")
                        .IsUnique();

                    b.ToTable("DocumentMetadatas");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("DocumentTemplates");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultProcessingDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypeConfigs");
                });

            modelBuilder.Entity("TrackNGoMati.Models.EscalationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualElapsedDays")
                        .HasColumnType("int");

                    b.Property<int>("ArtaperiodDays")
                        .HasColumnType("int")
                        .HasColumnName("ARTAPeriodDays");

                    b.Property<int>("Artathreshold")
                        .HasColumnType("int")
                        .HasColumnName("ARTAThreshold");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ElapsedDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EscalatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscalationLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<int?>("NotifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ViolatingOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_EscalationLogs_DocumentId");

                    b.HasIndex(new[] { "NotifiedUserId" }, "IX_EscalationLogs_NotifiedUserId");

                    b.HasIndex(new[] { "ResolvedByUserId" }, "IX_EscalationLogs_ResolvedByUserId");

                    b.ToTable("EscalationLogs");
                });

            modelBuilder.Entity("TrackNGoMati.Models.ExportAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExportScope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_ExportAuditLogs_UserId");

                    b.ToTable("ExportAuditLogs");
                });

            modelBuilder.Entity("TrackNGoMati.Models.QrcodeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrcodeImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QRCodeImagePath");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrackingUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_QRCodeRecords_DocumentId");

                    b.HasIndex(new[] { "TrackingNumber" }, "IX_QRCodeRecords_TrackingNumber")
                        .IsUnique();

                    b.ToTable("QRCodeRecords", (string)null);
                });

            modelBuilder.Entity("TrackNGoMati.Models.ReportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GeneratedByUserId" }, "IX_ReportLogs_GeneratedByUserId");

                    b.ToTable("ReportLogs");
                });

            modelBuilder.Entity("TrackNGoMati.Models.RoutingSlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionInstruction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("NotedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SlipStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TargetDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_RoutingSlips_DocumentId")
                        .IsUnique();

                    b.HasIndex(new[] { "NotedByUserId" }, "IX_RoutingSlips_NotedByUserId");

                    b.HasIndex(new[] { "ReceivedByUserId" }, "IX_RoutingSlips_ReceivedByUserId");

                    b.HasIndex(new[] { "TargetDepartmentId" }, "IX_RoutingSlips_TargetDepartmentId");

                    b.HasIndex(new[] { "TrackingNumber" }, "IX_RoutingSlips_TrackingNumber")
                        .IsUnique();

                    b.ToTable("RoutingSlips");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Smsnotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_SMSNotifications_DocumentId");

                    b.HasIndex(new[] { "RecipientUserId" }, "IX_SMSNotifications_RecipientUserId");

                    b.ToTable("SMSNotifications", (string)null);
                });

            modelBuilder.Entity("TrackNGoMati.Models.SystemNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SystemNotifications");
                });

            modelBuilder.Entity("TrackNGoMati.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExportPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOutOfOffice")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Users_DepartmentId");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrackNGoMati.Models.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedActions")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AssignedDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AssignedDepartmentId" }, "IX_WorkflowSteps_AssignedDepartmentId");

                    b.HasIndex(new[] { "TypeId" }, "IX_WorkflowSteps_TypeId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("TrackNGoMati.Models.WorkflowTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FromOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("ToOffice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DocumentId" }, "IX_WorkflowTransitions_DocumentId");

                    b.HasIndex(new[] { "PerformedByUserId" }, "IX_WorkflowTransitions_PerformedByUserId");

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("TrackNGoMati.Models.AuditTrailEntry", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("AuditTrailEntries")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGoMati.Models.User", "User")
                        .WithMany("AuditTrailEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Department", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "HeadUser")
                        .WithMany("Departments")
                        .HasForeignKey("HeadUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HeadUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DigitalSignature", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("DigitalSignatures")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "SignedByUser")
                        .WithMany("DigitalSignatures")
                        .HasForeignKey("SignedByUserId")
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SignedByUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Document", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "AssignedToUser")
                        .WithMany("DocumentsAssignedToUser")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_Documents_Users_AssignedToUserId");

                    b.HasOne("TrackNGoMati.Models.User", "CreatedByUser")
                        .WithMany("DocumentCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.Department", "Department")
                        .WithMany("Documents")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGoMati.Models.User", "SubmittedByUser")
                        .WithMany("DocumentSubmittedByUsers")
                        .HasForeignKey("SubmittedByUserId");

                    b.HasOne("TrackNGoMati.Models.DocumentTypeConfig", "Type")
                        .WithMany("Documents")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentAttachment", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("DocumentAttachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentComment", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("DocumentComments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "User")
                        .WithMany("DocumentComments")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentMetadata", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithOne("DocumentMetadata")
                        .HasForeignKey("TrackNGoMati.Models.DocumentMetadata", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentTemplate", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.EscalationLog", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("EscalationLogs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "NotifiedUser")
                        .WithMany("EscalationLogNotifiedUsers")
                        .HasForeignKey("NotifiedUserId");

                    b.HasOne("TrackNGoMati.Models.User", "ResolvedByUser")
                        .WithMany("EscalationLogResolvedByUsers")
                        .HasForeignKey("ResolvedByUserId");

                    b.Navigation("Document");

                    b.Navigation("NotifiedUser");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.ExportAuditLog", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "User")
                        .WithMany("ExportAuditLogs")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGoMati.Models.QrcodeRecord", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("QrcodeRecords")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("TrackNGoMati.Models.ReportLog", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "GeneratedByUser")
                        .WithMany("ReportLogs")
                        .HasForeignKey("GeneratedByUserId")
                        .IsRequired();

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.RoutingSlip", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithOne("RoutingSlip")
                        .HasForeignKey("TrackNGoMati.Models.RoutingSlip", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "NotedByUser")
                        .WithMany("RoutingSlipNotedByUsers")
                        .HasForeignKey("NotedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGoMati.Models.User", "ReceivedByUser")
                        .WithMany("RoutingSlipReceivedByUsers")
                        .HasForeignKey("ReceivedByUserId")
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.Department", "TargetDepartment")
                        .WithMany("RoutingSlips")
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("NotedByUser");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Smsnotification", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("Smsnotifications")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "RecipientUser")
                        .WithMany("Smsnotifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.SystemNotification", b =>
                {
                    b.HasOne("TrackNGoMati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackNGoMati.Models.User", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Department", "DepartmentNavigation")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DepartmentNavigation");
                });

            modelBuilder.Entity("TrackNGoMati.Models.WorkflowStep", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Department", "AssignedDepartment")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("AssignedDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TrackNGoMati.Models.DocumentTypeConfig", "Type")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepartment");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TrackNGoMati.Models.WorkflowTransition", b =>
                {
                    b.HasOne("TrackNGoMati.Models.Document", "Document")
                        .WithMany("WorkflowTransitions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackNGoMati.Models.User", "PerformedByUser")
                        .WithMany("WorkflowTransitions")
                        .HasForeignKey("PerformedByUserId")
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Department", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("RoutingSlips");

                    b.Navigation("Users");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("TrackNGoMati.Models.Document", b =>
                {
                    b.Navigation("AuditTrailEntries");

                    b.Navigation("DigitalSignatures");

                    b.Navigation("DocumentAttachments");

                    b.Navigation("DocumentComments");

                    b.Navigation("DocumentMetadata");

                    b.Navigation("EscalationLogs");

                    b.Navigation("QrcodeRecords");

                    b.Navigation("RoutingSlip");

                    b.Navigation("Smsnotifications");

                    b.Navigation("WorkflowTransitions");
                });

            modelBuilder.Entity("TrackNGoMati.Models.DocumentTypeConfig", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("TrackNGoMati.Models.User", b =>
                {
                    b.Navigation("AuditTrailEntries");

                    b.Navigation("Departments");

                    b.Navigation("DigitalSignatures");

                    b.Navigation("DocumentComments");

                    b.Navigation("DocumentCreatedByUsers");

                    b.Navigation("DocumentSubmittedByUsers");

                    b.Navigation("DocumentsAssignedToUser");

                    b.Navigation("EscalationLogNotifiedUsers");

                    b.Navigation("EscalationLogResolvedByUsers");

                    b.Navigation("ExportAuditLogs");

                    b.Navigation("ReportLogs");

                    b.Navigation("RoutingSlipNotedByUsers");

                    b.Navigation("RoutingSlipReceivedByUsers");

                    b.Navigation("Smsnotifications");

                    b.Navigation("WorkflowTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
